### ISSUE TITLE
Hovering over cell line shows data that is hard to see further

### ISSUE THREAD

**Issue by meclav** [gxa/atlas#2]
So I'm playing with the site and noticed the following on the experiments page, e.g.:
http://www.ebi.ac.uk/gxa/experiments/E-MTAB-2706?_specific=on&queryFactorType=CELL_LINE&queryFactorValues=&geneQuery=ASPM&exactMatch=true&serializedFilterFactors=

Hovering over the cell line element produces a table with details. The table is rather long so it doesn't fit on a laptop screen. In my browser (new Chrome) there isn't anything keeping the table on the screen after I hover off the element, so I can't scroll down and actually see the data inside it.

Perhaps clicking on the row could set the table element to "visible" until a click event or so.

**Comment by alfonsomunozpomer** [comment]
We’re aware of the issue and we’re looking at some alternatives. Currently we use jQuery-UI to show our tooltips but we’ll probably use [Bootstrap’s popovers](http://getbootstrap.com/javascript/#popovers) which will allow to dismiss the tooltip manually. This will also be an improvement for touch screen interfaces. We’ll keep the issue open until the tooltips are reimplemented.

**Comment by alfonsomunozpomer** [comment]
Dear Atlas developer,
Thank you for your feedback and your hard work in this problem. I’m closing the issue now for reasons you’re well aware of.
