### ISSUE TITLE
Wiki redirects to the repository's page

### ISSUE THREAD

**Issue by tr3vr** [gxa/atlas#3]
Hi, I was wondering if it would be possible to clone the project and setup an instance locally to test, but can't seem to find any documentation on how to go about doing this other than the UML diagrams themselves.

**Comment by alfonsomunozpomer** [comment]
Hi Trevor,

Thank you for your interest in Expression Atlas. The code of our project is on GitHub for documentation purposes and to help other users that face problems and challenges similar to ours. There are even parts that can be easily modifiable to be hosted elsewhere (i.e. React front-end components).

Unfortunately for your case, Expression Atlas is tightly coupled to the EBI infrastructure (DBMS, search engine and other internal services) so we don’t support replicating it and advise against it.

However we encourage you to visit Expression Atlas at http://www.ebi.ac.uk/gxa and use our range of services and features. We’ll be more than happy to hear any feedback or suggestion you may have.

Kind reagards,

Alfonso
